name: Deploy ke VPS

on:
  push:
    branches:
      - main  # Gantilah dengan branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/laravel/rosantibike-motorent
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm i
            npm run build
            composer i
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart nginx php8.2-fpm
